In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/since-2020.csv')
df.Date = pd.to_datetime(df.Date)
len(df)

24886

In [5]:
df = df.drop_duplicates(subset='ds', keep='first')

In [6]:
df = df.sort_values(by='ds', ascending=False)

In [7]:
df.ds = pd.to_datetime(df.ds)

In [10]:
df.Date = df['ds'].dt.strftime('%m/%d/%y')
df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,...,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission,ds,Total Pod TBS,Total Vertical TBS
0,11/07/22,21,6,118,2,126,8,244,2,39,...,0,0,0,1,4,10,6,2022-11-07 21:00:00,5,26
1,11/07/22,20,7,112,2,124,9,236,2,37,...,0,1,0,1,3,10,6,2022-11-07 20:00:00,2,32
2,11/07/22,19,5,105,8,122,13,227,1,35,...,0,3,0,1,4,8,6,2022-11-07 19:00:00,2,28
3,11/07/22,18,6,100,3,114,9,214,3,34,...,0,4,0,2,6,8,6,2022-11-07 18:00:00,3,30
4,11/07/22,17,3,94,6,111,9,205,3,31,...,0,4,0,2,11,9,6,2022-11-07 17:00:00,1,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24881,01/01/20,5,2,23,1,5,3,28,0,12,...,0,2,0,0,0,9,4,2020-01-01 05:00:00,2,7
24882,01/01/20,4,6,21,0,4,6,25,5,12,...,0,2,0,0,1,7,4,2020-01-01 04:00:00,3,8
24883,01/01/20,3,7,15,2,4,9,19,2,7,...,0,1,0,0,1,7,4,2020-01-01 03:00:00,0,11
24884,01/01/20,2,5,8,1,2,6,10,2,5,...,0,3,0,0,1,7,4,2020-01-01 02:00:00,3,7
24885,01/01/20,1,3,3,1,1,4,4,3,3,...,0,2,0,0,1,6,4,2020-01-01 01:00:00,2,5

In [20]:
df.to_csv('../data/since-2020.csv', index=False)

In [21]:
df = pd.read_csv('../data/since-2020.csv')
df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,...,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission,ds,Total Pod TBS,Total Vertical TBS
0,2022-11-07,21,6,118,2,126,8,244,2,39,...,0,0,0,1,4,10,6,2022-11-07 21:00:00,5,26
1,2022-11-07,20,7,112,2,124,9,236,2,37,...,0,1,0,1,3,10,6,2022-11-07 20:00:00,2,32
2,2022-11-07,19,5,105,8,122,13,227,1,35,...,0,3,0,1,4,8,6,2022-11-07 19:00:00,2,28
3,2022-11-07,18,6,100,3,114,9,214,3,34,...,0,4,0,2,6,8,6,2022-11-07 18:00:00,3,30
4,2022-11-07,17,3,94,6,111,9,205,3,31,...,0,4,0,2,11,9,6,2022-11-07 17:00:00,1,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24881,2020-01-01,5,2,23,1,5,3,28,0,12,...,0,2,0,0,0,9,4,2020-01-01 05:00:00,2,7
24882,2020-01-01,4,6,21,0,4,6,25,5,12,...,0,2,0,0,1,7,4,2020-01-01 04:00:00,3,8
24883,2020-01-01,3,7,15,2,4,9,19,2,7,...,0,1,0,0,1,7,4,2020-01-01 03:00:00,0,11
24884,2020-01-01,2,5,8,1,2,6,10,2,5,...,0,3,0,0,1,7,4,2020-01-01 02:00:00,3,7
24885,2020-01-01,1,3,3,1,1,4,4,3,3,...,0,2,0,0,1,6,4,2020-01-01 01:00:00,2,5

In [24]:
df.isna().sum()

Date                                    0
Time                                    0
Stretcher Pts hrly                      0
Stretcher Pts cum                       0
Ambulatory Pts hrly                     0
Ambulatory Pts cum                      0
Total Inflow hrly                       0
Total Inflow cum                        0
Ambulances hrly                         0
Ambulances cum                          0
FLS hrly                                0
Adm. requests cum                       0
Admissions cum                          0
Pts.waiting for admission CUM           0
Total Stretcher pts                     0
Triage hallway pts                      0
Triage hallway pts TBS                  0
Re-Oriented Nurse cum                   0
Re-Oriented MD QTrack D/C               0
Re-Oriented MD QTrack NotD/C            0
Resus Pts                               0
Totalpts in PODs except Psych           0
Green Pts                               0
Green Pts TBS                           0
Yellow PTS                              0
Yellow Pts TBS                          0
Orancge Pts except psych                0
Orange Pts TBS                          0
Consults > 2h in PODS except IM         0
Consult for IM >4h in PODS              0
Plain films reqs > 2 h in PODs          0
CTs reqs > 2 h in PODs                  0
Post POD (Family room)                  0
Stretcher Pts in Vertical               0
Stretcher Pts TBS in Vertical           0
Stretcher Pts in Vertical on Lazyboy    0
Vertical Pts Waiting for Results        0
Ambulatory Pts in Vertical              0
Ambulatory Pts TBS in Vertical          0
QTrack Patients TBS                     0
GARAGE patient TBS                      0
Consults > 2h in Vertical Except IM     0
Consult for IM >4h in Vertical          0
Plain films reqs > 2 hr in Vertical     0
CTs reqs > 2 hrs in Vertical            0
Psych Stretcher Pts1pt                  0
Psych pts waiting for admission         0
ds                                      0
Total Pod TBS                           0
Total Vertical TBS                      0
dtype: int64