In [2]:
import pandas as pd

In [4]:
# df = pd.DataFrame(columns=['time', 'y'])
df = pd.DataFrame()


for file in ['2020-01-03', '2020-04-06', '2020-07-09', '2020-10-12', '2021-01', '2021-02', '2021-03', '2021-04', '2021-05', '2021-06', '2021-07', '2021-08', '2021-09', '2021-10', '2021-11', '2021-12', '2022-01-01-09']:
    monthly_data = pd.read_csv(file+'.csv')
    columns = monthly_data.columns.to_list()
    columns.remove('dateflg')
    columns.remove('timeflg')
    data_list = []
    for i, row in monthly_data.iterrows():
        date = row['dateflg']
        time = row['timeflg']-1
#     total = row['Inflow_Total']
#     stretcher = row['INFLOW_STRETCHER']
#     ambulatory = row['INFLOW_AMBULATORY']
#     total_cum = row['Inflow_Cum_Total']
        time = pd.to_datetime(date + ' ' + str(time)+':00')
        dict_to_append = {}
        dict_to_append['time'] = time
#     data_list.append({'time':time, 'stretcher':stretcher, 'ambulatory':ambulatory,'total':total, 'total_cum':total_cum})
        for column in columns:
            dict_to_append[column] = row[column]
    
        data_list.append(dict_to_append)
        data_df = pd.DataFrame(data_list)
        df = pd.concat([df, data_df]).sort_values(by='time', ascending=True, ignore_index=True)
        df = df.drop_duplicates(keep='first')

df = df.set_index('time').resample('H').sum().reset_index()

df

,time,INFLOW_STRETCHER,Infl_Stretcher_cum,INFLOW_AMBULATORY,Infl_Ambulatory_cum,Inflow_Total,Inflow_Cum_Total,INFLOW_AMBULANCES,Infl_Ambulances_cum,FLS,...,AMBVERT1,AMBVERTTBS,QTrack_TBS,Garage_TBS,RAZ_CONS_MORE2H,RAZ_IMCONS_MORE4H,RAZ_XRAY_MORE2H,RAZ_CT_MORE2H1,PSYCH1,PSYCH_WAITINGADM
0,2020-01-01 00:00:00,3,3,1,1,4,4,3,3,0,...,2,2,0.0,0.0,2,0,0,1,6,4
1,2020-01-01 01:00:00,5,8,1,2,6,10,2,5,1,...,2,2,0.0,0.0,3,0,0,1,7,4
2,2020-01-01 02:00:00,7,15,2,4,9,19,2,7,1,...,5,5,0.0,0.0,1,0,0,1,7,4
3,2020-01-01 03:00:00,6,21,0,4,6,25,5,12,0,...,7,7,0.0,0.0,2,0,0,1,7,4
4,2020-01-01 04:00:00,2,23,1,5,3,28,0,12,0,...,1,1,0.0,0.0,2,0,0,0,9,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17744,2022-01-09 08:00:00,3,18,5,11,8,29,0,4,0,...,5,2,0.0,2.0,5,1,2,3,6,1
17745,2022-01-09 09:00:00,3,21,0,11,3,32,2,6,0,...,1,1,0.0,1.0,3,0,2,2,6,1
17746,2022-01-09 10:00:00,7,28,1,12,8,40,1,7,1,...,2,0,0.0,0.0,3,0,2,2,5,1
17747,2022-01-09 11:00:00,5,33,4,16,9,49,1,8,0,...,5,3,0.0,2.0,3,0,1,2,5,1
17748,2022-01-09 12:00:00,8,41,1,17,9,58,3,11,1,...,5,0,0.0,1.0,1,0,1,2,5,1

In [5]:
df.to_csv('concat.csv', index=False)

In [ ]:
df[['time', 'Inflow_Cum_Total']]

In [4]:
df = pd.DataFrame()


for file in ['2021-01', '2021-02', '2021-03', '2021-04', '2021-05', '2021-06', '2021-07', '2021-08', '2021-09', '2021-10']:
    monthly_data = pd.read_csv(file+'.csv')
    df = pd.concat([df, monthly_data]).sort_values(by=['dateflg', 'timeflg'], ascending=True, ignore_index=True)
    df = df.drop_duplicates(keep='first')

df

,dateflg,timeflg,INFLOW_STRETCHER,Infl_Stretcher_cum,INFLOW_AMBULATORY,Infl_Ambulatory_cum,Inflow_Total,Inflow_Cum_Total,INFLOW_AMBULANCES,Infl_Ambulances_cum,...,AMBVERT1,AMBVERTTBS,QTrack_TBS,Garage_TBS,RAZ_CONS_MORE2H,RAZ_IMCONS_MORE4H,RAZ_XRAY_MORE2H,RAZ_CT_MORE2H1,PSYCH1,PSYCH_WAITINGADM
0,01/01/21,1,1,1,1,1,2,2,0,0,...,0,0,NaN,NaN,1,0,0,0,3,3
1,01/01/21,2,2,3,1,2,3,5,1,1,...,2,2,NaN,NaN,1,1,0,0,3,3
2,01/01/21,3,0,3,1,3,1,6,0,1,...,2,1,NaN,NaN,0,0,0,0,3,3
3,01/01/21,4,1,4,0,3,1,7,1,2,...,2,0,NaN,NaN,0,0,0,0,4,3
4,01/01/21,5,1,5,1,4,2,9,1,3,...,1,1,NaN,NaN,0,0,0,0,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7334,11/01/21,20,4,123,4,123,8,246,2,35,...,20,16,0.0,2.0,2,0,0,0,10,2
7335,11/01/21,21,6,129,6,129,12,258,1,36,...,23,18,0.0,0.0,1,0,0,0,10,3
7336,11/01/21,22,2,131,5,134,7,265,2,38,...,23,17,0.0,0.0,2,0,0,0,8,3
7337,11/01/21,23,2,133,2,136,4,269,1,39,...,12,9,0.0,0.0,2,0,0,1,7,4
7338,11/01/21,24,1,134,1,137,2,271,1,40,...,8,8,0.0,0.0,2,0,0,0,6,4

In [6]:
output = pd.DataFrame()
for date in df.dateflg.unique():
    target = df[df.dateflg==date][['Inflow_Cum_Total']].reset_index(drop=True)
    target.columns = [date]
    target = target.transpose()
    output = pd.concat([output, target])
output.index = pd.to_datetime(output.index)
output

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
2021-01-01,2,5,6,7,9,12,14,16,23,33,...,85,98,106,112,119,123,132.0,135.0,138.0,141.0
2021-01-02,5,7,13,15,15,18,21,26,29,35,...,96,106,115,122,136,145,152.0,157.0,158.0,163.0
2021-01-03,4,9,12,13,14,15,18,22,24,35,...,94,107,123,129,138,144,151.0,159.0,164.0,172.0
2021-01-04,4,6,8,10,13,15,17,24,36,52,...,133,148,161,181,186,194,200.0,205.0,211.0,217.0
2021-01-05,4,5,9,10,12,12,15,24,39,53,...,124,140,151,160,170,181,196.0,199.0,206.0,209.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-28,3,6,9,12,14,15,16,21,28,42,...,136,153,168,176,187,195,201.0,212.0,222.0,228.0
2021-10-29,1,4,9,10,13,16,21,28,37,50,...,130,142,154,174,184,196,206.0,214.0,221.0,229.0
2021-10-30,5,9,11,17,19,23,29,39,50,62,...,144,155,157,167,177,184,196.0,204.0,209.0,212.0
2021-10-31,3,5,8,11,14,18,23,34,44,62,...,130,141,150,160,167,172,178.0,182.0,188.0,194.0
2021-11-01,2,6,10,12,14,18,19,28,45,60,...,180,189,206,221,238,246,258.0,265.0,269.0,271.0

In [7]:
output.to_csv('hourly_total_cum_inflow.csv')

In [9]:
df = pd.read_csv('concat.csv')
df['time'] = df['timeflg']-1
df['ds'] = pd.to_datetime(df.dateflg + ' ' + df['time'].apply(str)+':00')
df.set_index('ds', inplace=True)
df = df[['INFLOW_STRETCHER', 'INFLOW_AMBULATORY', 'Inflow_Total', 'INFLOW_AMBULANCES']]
df.to_csv('concat_clean.csv')